### ISSUE TITLE
bc3 confiure not working

### ISSUE THREAD

**Issue by amartya-dev** [phistrom/basecampy3#8]
When I try to configure using bc3 configure then it asks for client id and client secret upon entering which is required to enter email and passwords associated but the problem is I have my google account associated instead of normal email and password 

Thus the authentication fails and configure is unsuccessful. 

 Obtaining your access key and refresh token...
Traceback (most recent call last):
  File "C:\Users\Amartya\AppData\Local\Programs\Python\Python37-32\Scripts\bc3-script.py", line 11, in <module>
    load_entry_point('basecampy3==0.2.2', 'console_scripts', 'bc3')()
  File "c:\users\amartya\appdata\local\programs\python\python37-32\lib\site-packages\basecampy3\bc3_cli.py", line 122, in main
    return CLI.from_command_line()
  File "c:\users\amartya\appdata\local\programs\python\python37-32\lib\site-packages\basecampy3\bc3_cli.py", line 38, in from_command_line
    args.func()
  File "c:\users\amartya\appdata\local\programs\python\python37-32\lib\site-packages\basecampy3\bc3_cli.py", line 61, in _configure
    code = requestor.get_user_code()
  File "c:\users\amartya\appdata\local\programs\python\python37-32\lib\site-packages\basecampy3\token_requestor.py", line 53, in get_user_code
    user_code = self._submit_authorize_app_form(login_resp.url, login_resp.text)
  File "c:\users\amartya\appdata\local\programs\python\python37-32\lib\site-packages\basecampy3\token_requestor.py", line 98, in _submit_authorize_app_form
    auth_code = parse_qs(urlparse(app_redirect_uri).query)['code'][0]
KeyError: 'code'

**Comment by timecamp-analityk** [comment]
go to https://launchpad.37signals.com/integrations
see your integration settings, go to preview of Authorization dialog
click allow access, copy the code from url and run it through class method Basecamp3.trade_user_code_for_access_token
save json and use it to create instance of Basecamp3 objects

**Comment by amartya-dev** [comment]
I think it might be better to update the repo for using Basecamp 3 with the current O Auth 2.0, I was able to build something from scratch but I think in this repo you are trying to utilize the form-based input. I am not sure of it now but anyways I was trying that long ago...

**Comment by phistrom** [comment]
Hi guys, sorry for the long radio silence. I've had a lot going on at work and personal life since I began this project and haven't been able to care for it properly.

If memory serves correctly, I found the process of getting an Oauth token somewhat tedious, so I decided to implement a wizard that would use your username and password one time to obtain and save the necessary tokens (that's the token_requestor.py's job). It did this using the requests library to scrape the form at https://launchpad.37signals.com/integrations/new

That was a pretty dumb idea. I was trying to make it easier for users of this library, but by implementing a scraper like that, the littlest change to that form would break the wizard. Also I think they fairly quickly implemented reCAPTCHA or something similar (and I don't blame them) afterwards.

I'm going to do my best to update this library soon. It's in desperate need of security updates, and the wizard probably should just be removed.

**Comment by amartya-dev** [comment]
It is better to configure like the other libraries handling Oauth2.0, building one from the ground up will be good because the default libraries do not work with basecamp 3

**Comment by phistrom** [comment]
As promised, these these issues have finally been resolved and v0.3.0 is on PyPI. bc3 configure now attempts to open your web browser to your app's authorization page. The CLI will also listen on localhost:33333 for the code given when you authorize your integration. This means you should set your Basecamp integration's Redirect URI to http://localhost:33333 .

The user_email and password fields have been removed from BasecamPY3 entirely, but hopefully this is still a very easy setup process.
